import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MeetupList from '@/components/meetups/MeetupList'
// import { resolve } from 'styled-jsx/css'
import { useState } from 'react'
import { MongoClient } from 'mongodb'

const inter = Inter({ subsets: ['latin'] })


  // const DUMMY_MEETUPS = [
  //   {
  //     id: 'm1',
  //     image: 'https://avatars.mds.yandex.net/i?id=0bbeb64e703799fff1baec4428fa02a2ec0c6f9a-9583697-images-thumbs&n=13',
  //     address: 'Some address 5',
  //     title: 'A First Meetup',
  //     description: 'Some description of the event'
  //   },
  //   {
  //     id: 'm2',
  //     image: 'https://avatars.mds.yandex.net/i?id=196e4b05bea915050a5e13bd8b3fa06d4fdeb70b-10207868-images-thumbs&n=13',
  //     address: 'Some address 15',
  //     title: 'A Second Meetup',
  //     description: 'Some description of the event'
  //   },
  
  // ]
  
  export default function Home(props) {
   
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MeetupList meetups={props.meetups}/>
      </main>
    </>
  )
}

  export  async function getStaticProps(params) {
    const client = await MongoClient.connect(
      "mongodb+srv://baktygul:4646@cluster0.ruc6vxy.mongodb.net/meetups?retryWrites=true&w=majority")
   
    const dataBase = client.db()
    const meetupCollection = dataBase.collection('meetups')
    const meetups = await meetupCollection.find().toArray()
  
        return {
        props: {
              meetups: meetups.map((meetup) => ({
                title: meetup.title,
                address: meetup.address,
                image: meetup.image,
                description: meetup.description,
                id: meetup._id.toString()
              }))
        },
        revalidate: 1
      }
  }
  
  



